name: mltraining

channels:
- conda-forge
- defaults
dependencies:
- python>=3.8
- chardet==4.0.0
- joblib==1.1.0
- matplotlib==3.5.2
- pandas==1.3.5
- seaborn==0.11.2
- scikit_learn==1.0.2
pip:
  - xgboost==1.6.1
  - protobuf==4.21.1
#   - scikit_learn==1.1.1


