name: ml_training

channels:
- conda-forge
- defaults
dependencies:
- python>=3.8
- chardet==4.0.0
- pandas==1.3.1
- protobuf==3.19.4
- pytz==2021.1
- requests==2.25.1
- numpy==1.18.5
- tqdm ==4.61.2
- patool==1.12
- xgboost==1.6.1
- scikit-learn

